/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPmVsOperationsRouteImport } from './routes/blog.pm-vs-operations'
import { Route as BlogOperationsProjectManagerRoleRouteImport } from './routes/blog.operations-project-manager-role'
import { Route as BlogHowToDocumentSopsRouteImport } from './routes/blog.how-to-document-sops'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPmVsOperationsRoute = BlogPmVsOperationsRouteImport.update({
  id: '/blog/pm-vs-operations',
  path: '/blog/pm-vs-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOperationsProjectManagerRoleRoute =
  BlogOperationsProjectManagerRoleRouteImport.update({
    id: '/blog/operations-project-manager-role',
    path: '/blog/operations-project-manager-role',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToDocumentSopsRoute = BlogHowToDocumentSopsRouteImport.update({
  id: '/blog/how-to-document-sops',
  path: '/blog/how-to-document-sops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-document-sops': typeof BlogHowToDocumentSopsRoute
  '/blog/operations-project-manager-role': typeof BlogOperationsProjectManagerRoleRoute
  '/blog/pm-vs-operations': typeof BlogPmVsOperationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-document-sops': typeof BlogHowToDocumentSopsRoute
  '/blog/operations-project-manager-role': typeof BlogOperationsProjectManagerRoleRoute
  '/blog/pm-vs-operations': typeof BlogPmVsOperationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-document-sops': typeof BlogHowToDocumentSopsRoute
  '/blog/operations-project-manager-role': typeof BlogOperationsProjectManagerRoleRoute
  '/blog/pm-vs-operations': typeof BlogPmVsOperationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/blog/how-to-document-sops'
    | '/blog/operations-project-manager-role'
    | '/blog/pm-vs-operations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/blog/how-to-document-sops'
    | '/blog/operations-project-manager-role'
    | '/blog/pm-vs-operations'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/sitemap.xml'
    | '/blog/how-to-document-sops'
    | '/blog/operations-project-manager-role'
    | '/blog/pm-vs-operations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogHowToDocumentSopsRoute: typeof BlogHowToDocumentSopsRoute
  BlogOperationsProjectManagerRoleRoute: typeof BlogOperationsProjectManagerRoleRoute
  BlogPmVsOperationsRoute: typeof BlogPmVsOperationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pm-vs-operations': {
      id: '/blog/pm-vs-operations'
      path: '/blog/pm-vs-operations'
      fullPath: '/blog/pm-vs-operations'
      preLoaderRoute: typeof BlogPmVsOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/operations-project-manager-role': {
      id: '/blog/operations-project-manager-role'
      path: '/blog/operations-project-manager-role'
      fullPath: '/blog/operations-project-manager-role'
      preLoaderRoute: typeof BlogOperationsProjectManagerRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-document-sops': {
      id: '/blog/how-to-document-sops'
      path: '/blog/how-to-document-sops'
      fullPath: '/blog/how-to-document-sops'
      preLoaderRoute: typeof BlogHowToDocumentSopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogHowToDocumentSopsRoute: BlogHowToDocumentSopsRoute,
  BlogOperationsProjectManagerRoleRoute: BlogOperationsProjectManagerRoleRoute,
  BlogPmVsOperationsRoute: BlogPmVsOperationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
